### ISSUE TITLE
CRASH on startup

### ISSUE THREAD

**Issue by Cynix32** [Matyrobbrt/MatyLib#3]
Title says it all
Crashlog: https://pastebin.com/pcNyjrqn

MC 1.16.5
Java 8
Forge 36.2.20
matylib-1.16.5-1.0.4.jar
urg-1.16.5-1.1.jar

**Comment by Matyrobbrt** [comment]
This is a weird crash, but fortunately I may know the cause of it. When I'll get home (in around 6 hours) I should be able to fix it

**Comment by Matyrobbrt** [comment]
@Cynix32 1.0.5 should fix this

**Comment by Matyrobbrt** [comment]
And yes, it is safe to use 1.0.5 for URG even tho it requires (in the mods.toml) 1.0.4
